### ISSUE TITLE
Adding / Edit / Removing devices via RESTful API

### ISSUE THREAD

**Issue by mastershin** [neiljones12/VoxelCloud-Python#9]
API should support adding/edit/removing of devices via RESTful interface - Currently, it seems device list is hard coded in ASP.Net

**Comment by neiljones12** [comment]
Added API's to Add / Edit / Remove devices

![capture](https://user-images.githubusercontent.com/1053868/42072502-ad1d0506-7b15-11e8-8a45-218d1726f96d.PNG)

**Comment by mastershin** [comment]
Is there an unit test to test device add/edit/del ?

**Comment by neiljones12** [comment]
Yes i have written unit tests for device add/edit/del 

![test](https://user-images.githubusercontent.com/1053868/42104869-2150b59a-7b83-11e8-999f-1d89dae219e3.PNG)

![test new](https://user-images.githubusercontent.com/1053868/42104858-11dd5992-7b83-11e8-9902-fbf1517b32f5.PNG)

**Comment by neiljones12** [comment]
Yes, I have written unit tests for device add/edit/del 

![test](https://user-images.githubusercontent.com/1053868/42104903-4a62ad8a-7b83-11e8-9647-4d79d4b48207.PNG)

![test new](https://user-images.githubusercontent.com/1053868/42104905-4c9096a8-7b83-11e8-9daf-7e4c772250d7.PNG)
